#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/movies
#    username: root
#    password: Suhaib@2001
#  jpa:
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8089
#
#
#  project:
#    poster: poster/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: Suhaib@2001
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

project:
  poster: poster/


base:
  url: "http://localhost:8080"


#
#server.port=8089
#//spring.security.user.name=durgesh
#//spring.security.user.password=durgesh
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/movies
#spring.datasource.username=springstudent
#spring.datasource.password=springstudent
#logging.level.org.springframework.jdbc.core=TRACE
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect